spring:
  application:
    name: autoposter
  datasource:
    url: jdbc:mysql://localhost:3306/autoposter
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

gemini:
  api:
    key: ${GEMINI_API_KEY}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    channel: ${TELEGRAM_CHANNEL}
    owner-id: ${TELEGRAM_OWNER_ID}

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
    channel-id: ${DISCORD_CHANNEL_ID}
 